trigger:
- none

variables:
- group: sbox_secret_keys
- group: sbox_tfstates_keys

pool:
  name: 'test'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.9'
  displayName: 'Terraform Installation'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'Sandbox'
    backendAzureRmResourceGroupName: $(TF_RG_NAME)
    backendAzureRmStorageAccountName: $(TF_STORAGE_ACCOUNT_NAME)
    backendAzureRmContainerName: $(TF_CONTAINER_NAME)
    backendAzureRmKey: $(OWNER_NAME).tfstate
  env:
    CLIENT_ID: $(CLIENT_ID)
    CLIENT_SECRET: $(CLIENT_SECRET)
    SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
    TENANT_ID: $(TENANT_ID)
  displayName: 'Terraform Init'

- task: TerraformCLI@0
  inputs:
    command: 'plan'
    environmentServiceName: 'Sandbox'
  env:
    CLIENT_ID: $(CLIENT_ID)
    CLIENT_SECRET: $(CLIENT_SECRET)
    SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
    TENANT_ID: $(TENANT_ID)
  displayName: 'Terraform Plan'

- task: TerraformCLI@0
  inputs:
    command: 'apply'
    environmentServiceName: 'Sandbox'
  env:
    CLIENT_ID: $(CLIENT_ID)
    CLIENT_SECRET: $(CLIENT_SECRET)
    SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
    TENANT_ID: $(TENANT_ID)
  displayName: 'Terraform Apply'
- task: TerraformCLI@0
  inputs:
    command: 'destroy'
    environmentServiceName: 'Sandbox'
  env:
    CLIENT_ID: $(CLIENT_ID)
    CLIENT_SECRET: $(CLIENT_SECRET)
    SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
    TENANT_ID: $(TENANT_ID)
  displayName: 'Terraform Destroy'