trigger:
- none

pool:
  name: 'test'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.9'
  displayName: 'Terraform Installation'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'AgileHub-Ark-Dev(ae1cfcb2-2928-405d-afd3-743efe4dddd8)'
    backendAzureRmResourceGroupName: $(TF_RG_NAME)
    backendAzureRmStorageAccountName: $(TF_STORAGE_ACCOUNT_NAME)
    backendAzureRmContainerName: $(TF_CONTAINER_NAME)
    backendAzureRmKey: sandbox.$(OWNER_NAME).tfstate
  env:
    ARM_CLIENT_ID: $(CLIENT_ID)
    ARM_CLIENT_SECRET: $(CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(TENANT_ID)
  displayName: 'Terraform Init'

- task: TerraformCLI@0
  inputs:
    command: 'plan'
    environmentServiceName: 'AgileHub-Ark-Dev(ae1cfcb2-2928-405d-afd3-743efe4dddd8)'
    commandOptions: '-var "OWNER=$OWNER_NAME" -var "enable_storage=$enable_storage" -var "enable_postgresql=$enable_postgresql" -var "enable_container_registry=$enable_container_registry" -var "CLIENT_ID=$CLIENT_ID" -var "CLIENT_SECRET=$CLIENT_SECRET" -var "SUBSCRIPTION_ID=$SUBSCRIPTION_ID" -var "TENANT_ID=$TENANT_ID"'
  env:
    ARM_CLIENT_ID: $(CLIENT_ID)
    ARM_CLIENT_SECRET: $(CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(TENANT_ID)
  displayName: 'Terraform Plan'

# - task: TerraformCLI@0
#   inputs:
#     command: 'apply'
#     environmentServiceName: 'AgileHub-Ark-Dev(ae1cfcb2-2928-405d-afd3-743efe4dddd8)'
#.  displayName: 'Terraform Apply'
