trigger:
- none

variables:
- group: sbox_secret_keys

pool:
  name: 'test'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.9'
  displayName: 'Terraform Installation'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'AgileHub-Ark-Dev(ae1cfcb2-2928-405d-afd3-743efe4dddd8)'
    backendAzureRmResourceGroupName: $(TF_RG_NAME)
    backendAzureRmStorageAccountName: $(TF_STORAGE_ACCOUNT_NAME)
    backendAzureRmContainerName: $(TF_CONTAINER_NAME)
    backendAzureRmKey: sandbox.$(OWNER_NAME).tfstate
  env:
    CLIENT_ID: $(CLIENT_ID)
    CLIENT_SECRET: $(CLIENT_SECRET)
    SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
    TENANT_ID: $(TENANT_ID)
  displayName: 'Terraform Init'

- task: TerraformCLI@0
  inputs:
    command: 'plan'
    environmentServiceName: 'AgileHub-Ark-Dev(ae1cfcb2-2928-405d-afd3-743efe4dddd8)'
    commandOptions: '-var "OWNER=$(OWNER_NAME)"'
  env:
    CLIENT_ID: $(CLIENT_ID)
    CLIENT_SECRET: $(CLIENT_SECRET)
    SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
    TENANT_ID: $(TENANT_ID)
  displayName: 'Terraform Plan'

# - task: TerraformCLI@0
#   inputs:
#     command: 'apply'
#     environmentServiceName: 'AgileHub-Ark-Dev(ae1cfcb2-2928-405d-afd3-743efe4dddd8)'
#.  displayName: 'Terraform Apply'
