trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.9'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'AgileHub-Ark-Dev(ae1cfcb2-2928-405d-afd3-743efe4dddd8)'
    backendAzureRmResourceGroupName: $(TFRG)
    backendAzureRmStorageAccountName: $(TFSTORAGEACCOUNT)
    backendAzureRmContainerName: $(TFCONTAINERNAME)
    backendAzureRmKey: sandbox.$(TEAM_NAME).tfstate

- task: TerraformCLI@0
  inputs:
    command: 'plan'
    environmentServiceName: 'AgileHub-Ark-Dev(ae1cfcb2-2928-405d-afd3-743efe4dddd8)'

# - task: TerraformCLI@0
#   inputs:
#     command: 'apply'
#     environmentServiceName: 'AgileHub-Ark-Dev(ae1cfcb2-2928-405d-afd3-743efe4dddd8)'
