parameters:
- name: owner
  displayName: Owner Name
  type: string
  default: warren
  values:
  - saurabh
  - stuart
  - david
  - warren
  - Julio
- name: Postgres # name of the parameter; required
  type: boolean # data type of the parameter; required
  default: false
- name: Storage # name of the parameter; required
  type: boolean # data type of the parameter; required
  default: false
- name: AKS # name of the parameter; required
  type: boolean # data type of the parameter; required
  default: false
- name: DataLake # name of the parameter; required
  type: boolean # data type of the parameter; required
  default: false
- name: ContainerRegistry # name of the parameter; required
  type: boolean # data type of the parameter; required
  default: false
- name: VNET # name of the parameter; required
  type: boolean # data type of the parameter; required
  default: false
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

- script: |
    echo Owner=${{ parameters.owner }}
    echo Tools to install ${{ parameters.Postgres }}
    echo Tools to install ${{ parameters.Storage }}
    echo Tools to install ${{ parameters.AKS }}
    echo Tools to install ${{ parameters.DataLake }}
    echo Tools to install ${{ parameters.ContainerRegistry }}
    echo Tools to install ${{ parameters.VNET }}
  displayName: 'Run a multi-line script'
